### PR TITLE
Various fix

### PR DESCRIPTION
**Pull request by Shougo**
I have fixed the problems.

### CODE REVIEW

**Comment by shun** [comment]
Thank you!

**Comment by shun** [comment]
Sorry, I just revert your PR after merge.
Because I can't get any result .

It seems `filter` would drop any result.
Why ddi you filter the result  by line `#30` ?
```
const ret = list.filter((e) => !e).map((e) => {
```

**Comment by Shougo** [comment]
Because I get empty result.

**Comment by Shougo** [comment]
Ah, 

```typescript
const ret = list.filter((e) => e).map((e) => {
```

is correct.  It needs to filter empty line.

It is generated by `      const list = new TextDecoder().decode(output).split(/\r?\n/);`

**Pull request merged**
